name: build
on:
  push:
    branches:
    - develop
    - main

    paths:
    # Only rebuild website when apps have changed
    - 'cwl-workflow/**'
    - .github/**
    - src/**

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: [app-wrs-coverage]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install cwltool
    - run: cwltool --validate cwl-workflow/${{ matrix.step }}.cwl

  version:
    needs: validate

    runs-on: ubuntu-latest

    outputs:
      app-version: ${{ steps.set-version.outputs.version }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install "transpiler-mate>=0.17.0"
    - run: transpiler-mate codemeta cwl-workflow/app-wrs-coverage.cwl
    - run: echo "APP_VERSION=$(cat codemeta.json | jq -r .softwareVersion )" >> $GITHUB_ENV
    - run: echo app version is $APP_VERSION
    - id: set-version
      run: echo "::set-output name=version::$APP_VERSION"

  test-runner:
    needs: version

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - run: |
        pip install -U pip setuptools wheel
        pip install .
        pip install nose2
    - run: |
        nose2

  container-build:

    needs: 
    - version
    - test-runner

    runs-on: ubuntu-latest

    strategy:
      matrix:
        step: ['app-wrs-coverage']

    steps:
    - uses: actions/checkout@v2
    - run: echo version ${{needs.version.outputs.app-version}}
    - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: build & push image
      run: |
        IMAGE_ID=ghcr.io/eoap/${{ matrix.step }}
        docker build --file Dockerfile --tag ${{ matrix.step }} .
        docker tag ${{ matrix.step }} $IMAGE_ID:${{needs.version.outputs.app-version}}
        docker push $IMAGE_ID:${{needs.version.outputs.app-version}}

  create-release:

    needs:
    - container-build
    - version

    runs-on: ubuntu-latest

    outputs:

      upload_url: ${{ steps.set-upload-url.outputs.upload_url }}

    steps:
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{needs.version.outputs.app-version}}
        tag_name: ${{needs.version.outputs.app-version}}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - id: set-upload-url
      run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"

  publish-artifacts:

    needs:
    - create-release
    - version

    runs-on: ubuntu-latest

    strategy:
      matrix:
        step: [app-wrs-coverage]

    steps:
    - uses: actions/checkout@v2
    - run: |
        set -x
        tag="ghcr.io/eoap/${{matrix.step}}:${{needs.version.outputs.app-version}}"
        docker pull ${tag}
        shatag=$( docker inspect ${tag} | yq -r '.[0]["RepoDigests"][0]' )
        s="wrs-coverage-tool" t="${shatag}" yq -i eval '(.$graph[] | select (.id == env(s)) ).requirements.DockerRequirement.dockerPull = env(t)' cwl-workflow/${{matrix.step}}.cwl
    - name: Cleanup downloads folder
      run: rm -rf downloads/*
    - run: |
        mkdir -p downloads
        cp cwl-workflow/${{matrix.step}}.cwl downloads/${{matrix.step}}-${{needs.version.outputs.app-version}}.cwl
    - run: pip install "cwl2ogc>=0.10.0" "cwl2puml>=0.29.0" "transpiler-mate>=0.17.0"
    - run: cwl2ogc --workflow-id wrs-coverage --output=./downloads/${{matrix.step}}-ogcapi_process-${{needs.version.outputs.app-version}}.json ./cwl-workflow/app-wrs-coverage.cwl
    - run: |
        cwl2puml --workflow-id wrs-coverage --output=./downloads ./cwl-workflow/app-wrs-coverage.cwl
        rm ./downloads/*.puml
        for f in ./downloads/*.png; do mv "$f" "./downloads/${{matrix.step}}-$(basename -- ${f%.png})-${{needs.version.outputs.app-version}}.png"; done
    - run: transpiler-mate codemeta --code-repository=`git remote get-url origin` --output=./downloads/${{matrix.step}}-codemeta-${{needs.version.outputs.app-version}}.json cwl-workflow/app-wrs-coverage.cwl
    - run: transpiler-mate datacite --output=./downloads/${{matrix.step}}-datacite-${{needs.version.outputs.app-version}}.json cwl-workflow/app-wrs-coverage.cwl
    - run: transpiler-mate ogcrecord --output=./downloads/${{matrix.step}}-ogcapi_record-${{needs.version.outputs.app-version}}.json cwl-workflow/app-wrs-coverage.cwl
    - run: |
        transpiler-mate invenio-publish \
        --base-url=https://sandbox.zenodo.org \
        --auth-token=${{ secrets.INVENIO_AUTH_TOKEN }} \
        --attach=./downloads/${{matrix.step}}-codemeta-${{needs.version.outputs.app-version}}.json \
        --attach=./downloads/${{matrix.step}}-datacite-${{needs.version.outputs.app-version}}.json \
        --attach=./downloads/${{matrix.step}}-ogcapi_record-${{needs.version.outputs.app-version}}.json \
        --attach=./downloads/${{matrix.step}}-state-${{needs.version.outputs.app-version}}.png \
        --attach=./downloads/${{matrix.step}}-component-${{needs.version.outputs.app-version}}.png \
        --attach=./downloads/${{matrix.step}}-activity-${{needs.version.outputs.app-version}}.png \
        ./downloads/${{matrix.step}}-${{needs.version.outputs.app-version}}.cwl

    - uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.step}}-${{needs.version.outputs.app-version}}
        path: downloads
        overwrite: true
    
    - name: upload application package to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{needs.create-release.outputs.upload_url}}
        asset_path: downloads/${{matrix.step}}-${{needs.version.outputs.app-version}}.cwl
        asset_name: ${{matrix.step}}-${{needs.version.outputs.app-version}}.cwl
        asset_content_type: text/yaml

    # codemeta

    - name: upload codemeta to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{needs.create-release.outputs.upload_url}}
        asset_path: downloads/${{matrix.step}}-codemeta-${{needs.version.outputs.app-version}}.json
        asset_name: ${{matrix.step}}-codemeta-${{needs.version.outputs.app-version}}.json
        asset_content_type: text/json

    # ogcapi_process

    - name: upload ogcapi_process to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{needs.create-release.outputs.upload_url}}
        asset_path: downloads/${{matrix.step}}-ogcapi_process-${{needs.version.outputs.app-version}}.json
        asset_name: ${{matrix.step}}-ogcapi_process-${{needs.version.outputs.app-version}}.json
        asset_content_type: text/json

    # ogcapi_record

    - name: upload ogcapi_record to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{needs.create-release.outputs.upload_url}}
        asset_path: downloads/${{matrix.step}}-ogcapi_record-${{needs.version.outputs.app-version}}.json
        asset_name: ${{matrix.step}}-ogcapi_record-${{needs.version.outputs.app-version}}.json
        asset_content_type: text/json

    # component

    - name: upload component to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{needs.create-release.outputs.upload_url}}
        asset_path: downloads/${{matrix.step}}-component-${{needs.version.outputs.app-version}}.png
        asset_name: ${{matrix.step}}-component-${{needs.version.outputs.app-version}}.png
        asset_content_type: image/png

    # # class

    # - name: upload class to release
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ${{needs.create-release.outputs.upload_url}}
    #     asset_path: downloads/${{matrix.step}}-class-${{needs.version.outputs.app-version}}.png
    #     asset_name: ${{matrix.step}}-class-${{needs.version.outputs.app-version}}.png
    #     asset_content_type: image/png

    # # sequence

    # - name: upload sequence to release
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ${{needs.create-release.outputs.upload_url}}
    #     asset_path: downloads/${{matrix.step}}-sequence-${{needs.version.outputs.app-version}}.png
    #     asset_name: ${{matrix.step}}-sequence-${{needs.version.outputs.app-version}}.png
    #     asset_content_type: image/png

    # state

    - name: upload state to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{needs.create-release.outputs.upload_url}}
        asset_path: downloads/${{matrix.step}}-state-${{needs.version.outputs.app-version}}.png
        asset_name: ${{matrix.step}}-state-${{needs.version.outputs.app-version}}.png
        asset_content_type: image/png

    # datacite

    - name: upload datacite to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{needs.create-release.outputs.upload_url}}
        asset_path: downloads/${{matrix.step}}-datacite-${{needs.version.outputs.app-version}}.json
        asset_name: ${{matrix.step}}-datacite-${{needs.version.outputs.app-version}}.json
        asset_content_type: text/json

    - name: Setup ORAS CLI
      uses: oras-project/setup-oras@v1
    
    - name: Push CWL as OCI Artifact to GHCR
      run: |
        set -x
        cd downloads
        FILE=${{matrix.step}}-${{needs.version.outputs.app-version}}.cwl
        NAME=ghcr.io/eoap/app-wrs-coverage/${{matrix.step}}:${{needs.version.outputs.app-version}}

        echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin

        oras push "$NAME" \
          --artifact-type application/cwl \
          "$FILE:application/cwl"